require "jmartinn.impatient"
require "jmartinn.options"
require "jmartinn.keymaps"
require "jmartinn.plugins"
require "jmartinn.autocommands"
require "jmartinn.colorscheme"
require "jmartinn.cmp"
require "jmartinn.telescope"
require "jmartinn.gitsigns"
require "jmartinn.treesitter"
require "jmartinn.autopairs"
require "jmartinn.comment"
require "jmartinn.nvimtree"
require "jmartinn.bufferline"
require "jmartinn.lualine"
-- require "jmartinn.toggleterm"
require "jmartinn.project"
require "jmartinn.illuminate"
require "jmartinn.indentline"
-- require "jmartinn.alpha"
require "jmartinn.lsp"
require "jmartinn.dap"
